### ISSUE TITLE
postgresql-13.1-modify 模块的改动不清晰

### ISSUE THREAD

**Issue by jarvis-kk** [Nathaniel-Han/End-to-End-CardEst-Benchmark#1]
benchmark 是在 pg 上做了一定的改动是的 pg 可以使用模型的预估基数结果，但是具体在开源版本上做了哪些改动不清晰。
希望能够提供展示变更的方式，可以考虑使用 git 的 submodule 来追踪。

**Comment by Nathaniel-Han** [comment]
Yes, 'git submodule' is good advice. However, it takes time to re-organize. Please note the purpose of this modified Postgres is just to validate the effectiveness of current ML-based methods. Therefore, it is *NOT* an industrial-level integration. If you are really interested in the modified strategy, please refer to `backend/utils/misc/guc.c` and `backend/optimizer/path/costsize.c`. Thanks.

**Comment by Nathaniel-Han** [comment]
现在已经提交了benchmark.patch, 可以比较清晰地看到postgresql的改动
