### ISSUE TITLE
can't open the website to download the dataset

### ISSUE THREAD

**Issue by Tename** [Nathaniel-Han/End-to-End-CardEst-Benchmark#10]
I want to use the stats to test my methods, but i can't open the https://relational.fit.cvut.cz/dataset/Stats.  The website prompts a 404 error.

**Comment by Tename** [comment]
sorry,I didn't read the readme.md carefully. I have find the dataset.

**Comment by Wangyibo321** [comment]
> sorry,I didn't read the readme.md carefully. I have find the dataset.
I can't find the original dataset, either. How did you find it?

**Comment by SEICS** [comment]
Hi, the original dataset seems to be here: https://relational-data.org/dataset/Stats.

Hope this helps.
