### ISSUE TITLE
The sub_queries of stats are wrong.

### ISSUE THREAD

**Issue by CaiNot** [Nathaniel-Han/End-to-End-CardEst-Benchmark#11]
This file *stats_CEB_sub_queries.sql* in `workloads/stats_CEB/sub_plan_queries/stats_CEB_sub_queries.sql` is wrong.

For example, the source query only contains 2 tables, but 3 tables are listed in sub_queries.
Additionally, any sub queries can only contain at most 2 tables for JOIN.

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/90a34060-786c-497e-9556-6b9ed8a32f3e">

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/be601c7c-03a6-42a9-ba1a-e56db7d91bdb">

**Comment by Nathaniel-Han** [comment]
We did manually add the table 'u' on purpose for Query 2. In this way, models that don't support FK-FK join conditions, such as DeepDB, can perform their inference on cardinality.
