### ISSUE TITLE
pg load data 语法错误

### ISSUE THREAD

**Issue by jarvis-kk** [Nathaniel-Han/End-to-End-CardEst-Benchmark#2]
https://github.com/Nathaniel-Han/End-to-End-CardEst-Benchmark/blob/master/scripts/sql/stats_load.sql

load data 应该使用  copy  table_name  from filename ， 缺少了 from 关键字

**Comment by Nathaniel-Han** [comment]
Thanks for your attention. We have just fix that. :)
