### ISSUE TITLE
想问一些问题

### ISSUE THREAD

**Issue by ghost** [Nathaniel-Han/End-to-End-CardEst-Benchmark#5]
您好，对您们的work非常感兴趣，想问一些问题，如下：
1.请问您们的benchmark中的负载的true cardinality是怎么获取的呢？
2.请问readme文档中的pg是使用的是原始的pg吗？

**Comment by Nathaniel-Han** [comment]
1.获取sub-plan queries之后，对于sub-plan query各自true cardinality的计算, 可以使用任何你身边可以获取的计算资源去计算，可以在postgresql本身跑出结果，也可以部署一个新的spark集群导入数据之后去计算，亦或其他的计算系统，只要保证结果正确即可
2.不是。在PostgreSQL13.1为了注入基数在query optimizer层进行了修改，具体修改请见benchmark.patch。或者你可以直接使用在backup分支已经打好patch的postgresql-13.1-modify

**Comment by ghost** [comment]
> 1.获取sub-plan queries之后，对于sub-plan query各自true cardinality的计算, 可以使用任何你身边可以获取的计算资源去计算，可以在postgresql本身跑出结果，也可以部署一个新的spark集群导入数据之后去计算，亦或其他的计算系统，只要保证结果正确即可
> 2.不是。在PostgreSQL13.1为了注入基数在query optimizer层进行了修改，具体修改请见benchmark.patch。或者你可以直接使用在backup分支已经打好patch的postgresql-13.1-modify

sub-plan-query是不是就是在查询树上，假如我想获取某个节点A的基数，我就以该节点A作为root节点，然后构建sub-query，将数据和sub-query导入到其他的计算系统去计算吗？

**Comment by Nathaniel-Han** [comment]
概念上是可以这么去理解， 只是经过parser/optimizer层sub-plan query并不是简单的sql语句形式，因为已经经过层层的处理成为中间的表示，需要自己做一层转换，具体可以看下相关源代码 :)
