### ISSUE TITLE
关于postgres基数注入的问题

### ISSUE THREAD

**Issue by mazhencr7** [Nathaniel-Han/End-to-End-CardEst-Benchmark#8]
老师您好，我们也在做不同基数估计方法比较的课题，看到了您的benchmark.patch的补丁，想问一下适用于哪个版本的pg数据库，怎么安装这个补丁呢？我们想实现基数注入，可以通过这个补丁修改pg数据库的基数为我们ml方法的基数吗？

**Comment by Nathaniel-Han** [comment]
readme有写是13.1
不用补丁的话也直接用backup分支编译也可
