### ISSUE TITLE
Questions about the patch for the estimated cardinality injection

### ISSUE THREAD

**Issue by Beliefuture** [Nathaniel-Han/End-to-End-CardEst-Benchmark#9]
Hi,

For the integration of the CardEst methods into PostgreSQL, I wonder the difference of this implemented functionality compared with the corresponding hint provided in `pg_hint_plan` (https://github.com/ossc-db/pg_hint_plan).

**Comment by Nathaniel-Han** [comment]
I believe this tool provides a more flexible but hack way to inject the cardinality of a specific workload.
